### ISSUE TITLE
Setup Guide for MCP Media Generator

### ISSUE THREAD

**Issue by ldavis9000aws** [dvejsada/mcp_media_generator#3]
Do you have a setup guide people can follow on how to implement this based on the type of LibreChat install being used (docker vs local install)?

**Comment by dvejsada** [comment]
Closed by #5. Provided more detailed instructions for usage.

**Comment by ldavis9000aws** [comment]
@dvejsada Thanks - Initially, the mcp server could not be contacted:

```
MCP-Media-Creator  | INFO:mcp-media-creator:Starting MCP Media Creator
MCP-Media-Creator  | DEBUG:mcp.server.lowlevel.server:Initializing server 'pptx_presentation'
MCP-Media-Creator  | DEBUG:mcp.server.lowlevel.server:Registering handler for ListToolsRequest
MCP-Media-Creator  | DEBUG:mcp.server.lowlevel.server:Registering handler for CallToolRequest
MCP-Media-Creator  | DEBUG:mcp.server.sse:SseServerTransport initialized with endpoint: /messages/
MCP-Media-Creator  | DEBUG:asyncio:Using selector: EpollSelector
MCP-Media-Creator  | INFO:uvicorn.error:Started server process [7]
MCP-Media-Creator  | INFO:uvicorn.error:Waiting for application startup.
MCP-Media-Creator  | INFO:uvicorn.error:Application startup complete.
MCP-Media-Creator  | INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8961 (Press CTRL+C to quit)
```

```
LibreChat         | 2025-02-03 17:25:30 info: [MCP][media-creator] Connection state: disconnected
LibreChat         | 2025-02-03 17:25:30 info: [MCP][media-creator] Connection state: connecting
LibreChat         | 2025-02-03 17:25:30 info: [MCP][media-creator] Creating SSE transport: http://localhost:8961/sse
LibreChat         | 2025-02-03 17:25:30 info: [MCP][media-creator] Connection state: error
LibreChat         | 2025-02-03 17:25:30 error: [MCP][media-creator] Connection failed: SSE error: {}
LibreChat         | 2025-02-03 17:25:30 error: [MCP][media-creator] Failed after 3 attempts
LibreChat         | 2025-02-03 17:25:30 error: [MCP][media-creator] Initialization failed SSE error: {}
LibreChat         | 2025-02-03 17:25:30 info: [MCP] Initialized 0/1 server(s)
LibreChat         | 2025-02-03 17:25:30 warn: [MCP] 1/1 server(s) failed to initialize
LibreChat         | 2025-02-03 17:25:30 info: [MCP][media-creator] ✗ Failed
LibreChat         | 2025-02-03 17:25:30 error: [MCP] No servers initialized
```

The MCP server was running on the same EC2 instance as Librechat (running in docker). After doing some troubleshooting with Claude via Bedrock, I added the container to the same docker network as Librechat and modified the URL to reference the mcp docker container name. Once I did that & restarted both the mcp server & LibreChat, they were able to communicate. I also modified the docker-compose.yml file for the mcp server to pull environment variables from a .env file rather than hardcoding credentials into the docker-compose.yml file. 

Librechat.yml

```
mcpServers:
  media-creator: 
    type: sse # type can optionally be omitted
    url: http://mcp-media-creator:8961/sse
```

docker-compose.yml 

```
networks:
  librechat_default:
    external: true
services:
  Media_creator:
    image: georgx22/mcp-media-creator:latest
    container_name: MCP-Media-Creator
    restart: always
    ports:
      - "8961:8961"
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
    networks:
      - librechat_default
```

I should probably be using an IAM profile or Parameter Store to pull those credentials, but this works for testing purposes. I was able to successfully generate images using the tool. Thank you!
